import iconPhone from "../../../../assets/Final small icon images white svg/Icon phone-white.svg";

export const HeroBackground = (props: { cms?: { src?: string; alt?: string } }) => {
  const src = props.cms?.src || "/placeholders/plan-hero.svg";
  const alt = props.cms?.alt || "Дом 1";

  return (
    <div className="static box-content caret-black h-auto outline-black w-auto left-auto top-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:h-[625.792px] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-screen md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:top-0">
      <div className="static box-content caret-black h-auto outline-black w-auto md:relative md:aspect-auto md:box-border md:caret-transparent md:h-full md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static box-content caret-black h-auto outline-black w-auto inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:h-full md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0">
          <img
            src={src}
            alt={alt}
            className="static box-content caret-black h-auto max-w-none object-fill object-[50%_50%] outline-black w-auto inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:h-full md:max-w-full md:object-cover md:object-[-320px_50%] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"
          />
        </div>
        <div className="static box-content caret-black h-auto opacity-100 outline-black w-auto inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:h-full md:opacity-0 md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0">
          <img
            src="/placeholders/plan-hero.svg"
            alt="Дом 2"
            className="static box-content caret-black h-auto max-w-none object-fill object-[50%_50%] outline-black w-auto inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:h-full md:max-w-full md:object-cover md:object-[-320px_50%] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"
          />
        </div>
        <div className="static box-content caret-black h-auto opacity-100 outline-black w-auto inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:h-full md:opacity-0 md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0">
          <img
            src="/placeholders/plan-hero.svg"
            alt="Дом 3"
            className="static box-content caret-black h-auto max-w-none object-fill object-[50%_50%] outline-black w-auto inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:h-full md:max-w-full md:object-cover md:object-[-320px_50%] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"
          />
        </div>
        <div className="static box-content caret-black h-auto opacity-100 outline-black w-auto inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:h-full md:opacity-0 md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0">
          <img
            src="/placeholders/plan-hero.svg"
            alt="Дом 4"
            className="static box-content caret-black h-auto max-w-none object-fill object-[50%_50%] outline-black w-auto inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:h-full md:max-w-full md:object-cover md:object-[-320px_50%] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"
          />
        </div>
        <div className="static box-content caret-black h-auto opacity-100 outline-black w-auto inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:h-full md:opacity-0 md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0">
          <img
            src="/placeholders/plan-hero.svg"
            alt="Дом 5"
            className="static box-content caret-black h-auto max-w-none object-fill object-[50%_50%] outline-black w-auto inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:h-full md:max-w-full md:object-cover md:object-[-320px_50%] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"
          />
        </div>
      </div>
      <div className="static bg-none box-content caret-black h-auto outline-black w-auto left-auto bottom-auto md:absolute md:aspect-auto md:bg-[linear-gradient(in_oklab,rgba(0,0,0,0)_0%,rgb(0,0,0)_100%)] md:box-border md:caret-transparent md:h-[252.416px] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[880.896px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:bottom-0"></div>
      <div className="static box-content caret-black gap-x-[normal] block outline-black gap-y-[normal] z-auto left-auto top-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:gap-x-[12.8px] md:flex md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-[12.8px] md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-10 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-[51.2px] md:top-[576px]">
        <div className="bg-transparent shadow-none box-content caret-black h-auto min-h-0 min-w-0 outline-black w-auto rounded-none md:aspect-auto md:bg-white md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0.1)_0px_10px_15px_-3px,rgba(0,0,0,0.1)_0px_4px_6px_-4px] md:box-border md:caret-transparent md:h-[12.8px] md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[12.8px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[3.35544e+07px]"></div>
        <div className="bg-transparent shadow-none box-content caret-black h-auto min-h-0 min-w-0 opacity-100 outline-black w-auto rounded-none md:aspect-auto md:bg-white md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0.1)_0px_10px_15px_-3px,rgba(0,0,0,0.1)_0px_4px_6px_-4px] md:box-border md:caret-transparent md:h-[12.8px] md:min-h-[auto] md:min-w-[auto] md:opacity-35 md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[12.8px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[3.35544e+07px]"></div>
        <div className="bg-transparent shadow-none box-content caret-black h-auto min-h-0 min-w-0 opacity-100 outline-black w-auto rounded-none md:aspect-auto md:bg-white md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0.1)_0px_10px_15px_-3px,rgba(0,0,0,0.1)_0px_4px_6px_-4px] md:box-border md:caret-transparent md:h-[12.8px] md:min-h-[auto] md:min-w-[auto] md:opacity-35 md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[12.8px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[3.35544e+07px]"></div>
        <div className="bg-transparent shadow-none box-content caret-black h-auto min-h-0 min-w-0 opacity-100 outline-black w-auto rounded-none md:aspect-auto md:bg-white md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0.1)_0px_10px_15px_-3px,rgba(0,0,0,0.1)_0px_4px_6px_-4px] md:box-border md:caret-transparent md:h-[12.8px] md:min-h-[auto] md:min-w-[auto] md:opacity-35 md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[12.8px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[3.35544e+07px]"></div>
        <div className="bg-transparent shadow-none box-content caret-black h-auto min-h-0 min-w-0 opacity-100 outline-black w-auto rounded-none md:aspect-auto md:bg-white md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0.1)_0px_10px_15px_-3px,rgba(0,0,0,0.1)_0px_4px_6px_-4px] md:box-border md:caret-transparent md:h-[12.8px] md:min-h-[auto] md:min-w-[auto] md:opacity-35 md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[12.8px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[3.35544e+07px]"></div>
      </div>
      <div className="static [align-items:normal] box-content caret-black gap-x-[normal] block flex-row justify-normal outline-black gap-y-[normal] right-auto top-auto md:absolute md:items-end md:aspect-auto md:box-border md:caret-transparent md:gap-x-[2.176px] md:flex md:flex-col md:justify-center md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-[2.176px] md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:right-[606.208px] md:top-[35.584px]">
        <div className="static text-base font-normal box-content caret-black shrink leading-[normal] min-h-0 min-w-0 outline-black text-wrap md:relative md:text-[13.312px] md:font-medium md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:leading-[0px] md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <a
            href="mailto://david@houseofwatkins.com"
            className="text-black box-content caret-black leading-[normal] outline-black text-wrap md:text-white md:aspect-auto md:box-border md:caret-transparent md:leading-[19.584px] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
          >
            david@houseofwatkins.com
          </a>
        </div>
        <div className="static [align-items:normal] box-content caret-black gap-x-[normal] block shrink justify-normal min-h-0 min-w-0 outline-black gap-y-[normal] md:relative md:items-center md:aspect-auto md:box-border md:caret-transparent md:gap-x-[1.792px] md:flex md:shrink-0 md:justify-start md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-[1.792px] md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static box-content caret-black shrink h-auto min-h-0 min-w-0 outline-black w-auto md:relative md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:h-[17.792px] md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[17.792px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            <div className="static box-content caret-black block outline-black inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:contents md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0">
              <img
                src={(iconPhone as any).src ?? (iconPhone as any)}
                alt="Icon"
                className="box-content caret-black h-auto outline-black w-auto md:aspect-auto md:box-border md:caret-transparent md:h-full md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
              />
            </div>
          </div>
          <div className="static font-normal box-content caret-black shrink leading-[normal] min-h-0 min-w-0 outline-black text-wrap md:relative md:font-semibold md:aspect-auto md:box-border md:caret-transparent md:shrink-0 md:leading-[0px] md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            <a
              href="tel://+15412191673"
              className="text-black box-content caret-black leading-[normal] outline-black text-wrap md:text-white md:aspect-auto md:box-border md:caret-transparent md:leading-[21.376px] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"
            >
              +1 541 219 1673
            </a>
          </div>
        </div>
      </div>
      <div className="static box-content caret-black h-auto outline-black w-auto left-auto top-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:h-[2.688px] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[2.688px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-12 md:top-[557.312px]"></div>
      <button className="static bg-zinc-100 caret-black inline-block shrink h-auto outline-black w-auto left-auto top-auto md:absolute md:aspect-auto md:bg-transparent md:caret-transparent md:block md:shrink-0 md:h-[34.688px] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[84.736px] md:[mask-position:0%] md:bg-left-top md:p-0 md:scroll-m-0 md:scroll-p-[auto] md:left-[56.832px] md:top-[35.584px]">
        <div className="static bg-none bg-repeat bg-auto box-content caret-black outline-black inset-auto md:absolute md:aspect-auto md:bg-[url('/placeholders/plan-hero.svg')] md:bg-no-repeat md:bg-size-[128.22%_214.2%] md:box-border md:caret-transparent md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-[position:52.14%_41.18%] md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
      </button>
    </div>
  );
};
