export const ImageGallery = () => {
  return (
    <div className="box-content caret-black gap-x-[normal] block grid-cols-none grid-rows-none h-auto min-h-0 min-w-0 outline-black gap-y-[normal] w-auto md:aspect-auto md:box-border md:caret-transparent md:gap-x-[1.792px] md:grid md:grid-cols-[593.792px_1fr_1fr] md:grid-rows-[1fr_1fr] md:h-[410.624px] md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-[1.792px] md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
      <div className="bg-none bg-repeat bg-auto box-content caret-black row-end-auto row-start-auto min-h-0 min-w-0 outline-black rounded-l-none md:aspect-auto md:bg-[url('https://moss-nix-41841216.figma.site/_assets/v11/0d7da24ac0bafe7483e1f21855c531a9e32c00c5.png')] md:bg-no-repeat md:bg-cover md:box-border md:caret-transparent md:row-end-[span_2] md:row-start-[span_2] md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-center md:scroll-m-0 md:scroll-p-[auto] md:rounded-l-[35.584px]"></div>
      <div className="bg-none bg-repeat bg-auto box-content caret-black row-end-auto row-start-auto min-h-0 min-w-0 outline-black md:aspect-auto md:bg-[url('https://c.animaapp.com/mjfxgf97dMquCY/assets/fc0b8bea3094e03cae05bbe76bb198c7fd38be5c.png')] md:bg-no-repeat md:bg-cover md:box-border md:caret-transparent md:row-end-[span_2] md:row-start-[span_2] md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-center md:scroll-m-0 md:scroll-p-[auto]"></div>
      <div className="static bg-none bg-repeat bg-auto box-content caret-black min-h-0 min-w-0 outline-black rounded-tr-none md:relative md:aspect-auto md:bg-[url('https://c.animaapp.com/mjfxgf97dMquCY/assets/e6e4ee5f6f56e6649ea7a85fd46aef92d99d93cb.png')] md:bg-no-repeat md:bg-cover md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-center md:scroll-m-0 md:scroll-p-[auto] md:rounded-tr-[35.584px]">
        <div className="static box-content caret-black outline-black pointer-events-auto rounded-tr-none inset-auto md:absolute md:aspect-auto md:box-border md:caret-transparent md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:pointer-events-none md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:border md:border-stone-200 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-tr-[35.584px] md:border-solid md:inset-0"></div>
      </div>
      <div className="static bg-none bg-repeat bg-auto box-content caret-black min-h-0 min-w-0 outline-black rounded-br-none md:relative md:aspect-auto md:bg-[url('https://moss-nix-41841216.figma.site/_assets/v11/5cd2dfd00bfd5adcb5ed9bc2278943dc059d340c.png')] md:bg-no-repeat md:bg-cover md:box-border md:caret-transparent md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-clip md:[mask-position:0%] md:bg-center md:scroll-m-0 md:scroll-p-[auto] md:rounded-br-[35.584px]">
        <button className="static [align-items:normal] self-auto bg-zinc-100 shadow-none caret-black gap-x-[normal] inline-block justify-normal outline-black gap-y-[normal] px-1.5 py-px rounded-none right-auto bottom-auto md:absolute md:items-center md:self-stretch md:aspect-auto md:bg-zinc-800 md:shadow-[rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0)_0px_0px_0px_0px,rgba(0,0,0,0.07)_0px_4px_4px_0px] md:caret-transparent md:gap-x-[8.832px] md:flex md:justify-center md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-[8.832px] md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:px-[17.792px] md:py-[8.832px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-[31.104px] md:right-[17.792px] md:bottom-[17.792px]">
          <div className="static text-black text-base font-normal box-content caret-black block flex-row shrink justify-normal tracking-[normal] leading-[normal] min-h-0 min-w-0 outline-black normal-case text-wrap md:relative md:text-white md:text-[13.312px] md:font-semibold md:aspect-auto md:box-border md:caret-transparent md:flex md:flex-col md:shrink-0 md:justify-center md:tracking-[0.128px] md:leading-[0px] md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:uppercase md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            <p className="box-content caret-black leading-[normal] min-h-0 min-w-0 outline-black text-wrap md:aspect-auto md:box-border md:caret-transparent md:leading-[21.376px] md:min-h-[auto] md:min-w-[auto] md:outline-[oklab(0.708_0_0_/_0.5)] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
              view all (7)
            </p>
          </div>
        </button>
      </div>
    </div>
  );
};
